In [1]:
import numpy as np
a=np.zeros(20)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
a[3]=5
print(a)

[0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
array_master=np.ones(20)
array_copy=array_master.copy()
print(array_master)
print(array_copy)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
c=np.ones(30)
c[:]=100
print(c)

[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100.]


In [9]:
array1=np.arange(21,31)
array2=np.arange(11,21)
r=array1 - array2
print(array1)
print(array2)
print(r)

[21 22 23 24 25 26 27 28 29 30]
[11 12 13 14 15 16 17 18 19 20]
[10 10 10 10 10 10 10 10 10 10]


In [12]:
a1=np.arange(2,11,2)
a2=np.arange(22,31,2)
c=np.stack((a1,a2))
print(c)

[[ 2  4  6  8 10]
 [22 24 26 28 30]]


In [13]:
d=np.column_stack((a1,a2))
print(d)

[[ 2 22]
 [ 4 24]
 [ 6 26]
 [ 8 28]
 [10 30]]


In [18]:
#Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column
array=np.arange(30).reshape(5,6)
print(array)
print(array[1,2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
8


In [23]:
#Create an identity matrix of shape 10x10 and replace the 0's with the value 21
arr=np.eye(10)
arr[arr==0]=21
print(arr)

[[ 1. 21. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21.  1. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21.  1. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21.  1. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21.  1. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21.  1. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21.  1. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21.  1. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21.  1. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21. 21.  1.]]


In [26]:
#Use NumPy to generate a random set of 10 numbers between 0 and 1
array=np.random.rand(10)
print(array)
	#Display a boolean array output where all values > 0.2 are True, rest are marked as False
print(array>0.2)


[0.11428327 0.59171988 0.60698712 0.68283854 0.94338118 0.8313911
 0.79036811 0.14122521 0.63060023 0.70309521]
[False  True  True  True  True  True  True False  True  True]


In [27]:
#Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution
arr=np.random.rand(5,2)
print(arr)

[[0.90327218 0.64322087]
 [0.00953401 0.19669234]
 [0.26042473 0.22813242]
 [0.24681299 0.64528885]
 [0.57599342 0.52900367]]


In [28]:
#Create an array of 30 linearly spaced points between 0 and 100:
arr=np.linspace(0,100,30)
print(arr)

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


In [47]:
#Using the below given Matrix, generate the output for the below questions
simple_matrix = np.arange(1,101).reshape(10,10)
print(simple_matrix)
#a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique
a=simple_matrix[8:,0:3]
a
#b) Retrieve the value 55 from the above matrix using index & selection technique
b=simple_matrix[5,4]
b
#c) Retrieve the values from the 3rd column in the above matrix
c=simple_matrix[:,2]
c
#) Retrieve the values from the 4th row in the above matrix
d=simple_matrix[3,:]
d
#e) Retrieve values from the 2nd & 4th rows in the above matrix
e=simple_matrix[(1,3),:]
e

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [49]:
#a) Calculate sum of all the values in the matrix
a=simple_matrix.sum()
a

5050

In [50]:
#b) Calculate standard deviation of all the values in the matrix
b=simple_matrix.std()
b

28.86607004772212

In [51]:
#c) Calculate the variance of all values in the matrix
c=simple_matrix.var()
c

833.25

In [52]:
#d) Calculate the mean of all values in the matrix
d=simple_matrix.mean()
d

50.5

In [53]:
#e) Retrieve the largest number from the matrix
e=simple_matrix.max()
e

100

In [54]:
#f) Retrieve the smallest number from the matrix
f=simple_matrix.min()
f

1