In [5]:
import numpy as np
#create vector
a=np.array([1,2,4,5])

print(a)

[1 2 4 5]


In [9]:
#vector dengan range
b=np.arange(1,9,0.5)

print(b)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


In [13]:
#create linspace a.k.a dibagi
c=np.linspace(1,100,5)
print(c)

[  1.    25.75  50.5   75.25 100.  ]


In [16]:
#create matriks
d=np.array([(1,2,3),(4,5,6)])
print(d)

[[1 2 3]
 [4 5 6]]


In [17]:
#create vector w/ 0's 
e=np.zeros(5)
print(e)

[0. 0. 0. 0. 0.]


In [22]:
#create matriks w/ 0's
f=np.zeros((5,5)) #.ones
print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
#matrix identity
g1=np.identity((3))
g2=np.eye((4))
print(g2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#matrix methode 2 arrays as rows
h1=np.array([1,2,3])
h2=np.array([4,5,6])
h3=np.stack((h1,h2))
print(h3)

[[1 2 3]
 [4 5 6]]


In [27]:
#matrix methode 2 arrays as collumn
g1=np.array([12,13,14])
g2=np.array([22,23,24])
g3=np.column_stack((g1,g2))
print(g3)

[[12 22]
 [13 23]
 [14 24]]
